groups:
- name: Садовое кольцо
  order: 1
  results:
    A: https://results.zone/ring-2024/races/7257/results
    B: https://results.zone/ring-2024/races/7258/results
    C: https://results.zone/ring-2024/races/7259/results
    F: https://results.zone/ring-2024/races/7261/results

- name: Верея
  order: 4
  results:
    A: https://results.zone/cyclingrace-verey-2024/races/7306/results
    B: https://results.zone/cyclingrace-verey-2024/races/7307/results
    C: https://results.zone/cyclingrace-verey-2024/races/7308/results
    F: https://results.zone/cyclingrace-verey-2024/races/7309/results

time-trials:
- name: Крылатские холмы
  order: 2
  results: https://results.zone/cyclingrace-tt-2024/races/7265/results

- name: Верея ITT
  order: 3
  results: https://results.zone/cyclingrace-vereyitt-2024/races/7305/results