rating-dir: data/rating
local_storage: data/races
races:
- name: Садовое кольцо
  tt-name: Крылатские холмы
  tt-first: False
  year-fixes: data/garden-ring/right-years.yml
  clusters: data/garden-ring/clusters.yml
  group:
    A: https://results.zone/ring-2024/races/7257/results
    B: https://results.zone/ring-2024/races/7258/results
    C: https://results.zone/ring-2024/races/7259/results
    F: https://results.zone/ring-2024/races/7261/results
  tt: https://results.zone/cyclingrace-tt-2024/races/7265/results

- name: Верея
  group:
    A: https://results.zone/cyclingrace-verey-2024/races/7306/results
    B: https://results.zone/cyclingrace-verey-2024/races/7307/results
    C: https://results.zone/cyclingrace-verey-2024/races/7308/results
    F: https://results.zone/cyclingrace-verey-2024/races/7309/results
  tt: https://results.zone/cyclingrace-vereyitt-2024/races/7305/results

- name: Дубна
  group:
    A: https://results.zone/tula_shosse_2024/races/7356/results
    B: https://results.zone/tula_shosse_2024/races/7357/results
    C: https://results.zone/tula_shosse_2024/races/7358/results
    F: https://results.zone/tula_shosse_2024/races/7359/results
  tt: https://results.zone/tula_2024/races/7353/results

- name: Столица
  group:
    A: https://results.zone/cyclingrace-stolica-2024/races/7403/results
    B: https://results.zone/cyclingrace-stolica-2024/races/7404/results
    C: https://results.zone/cyclingrace-stolica-2024/races/7405/results
    F: https://results.zone/cyclingrace-stolica-2024/races/7406/results
